name: Build Test

on:
  push:
    branches: [ "main", "indev" ]
  pull_request:
    branches: [ "main", "indev" ]

jobs:
  Linux:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Install dependencies
        run: |
          sudo add-apt-repository -y "deb http://archive.ubuntu.com/ubuntu `lsb_release -sc` main universe restricted multiverse"
          sudo apt-get update -y -qq
          sudo apt-get install libncurses5-dev
      - name: CMake build
        run: |
          mkdir build
          cd build
          cmake -DCMAKE_BUILD_TYPE=RELEASE -DWARNINGS_AS_ERRORS:BOOL=ON ..
          make -j

  Windows:
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: CMake build
        run: |
          mkdir build
          cd build
          cmake -DCMAKE_BUILD_TYPE=RELEASE -DWARNINGS_AS_ERRORS:BOOL=ON -G"MinGW Makefiles" ..
          make -j
